initial commit of working Ogg
libretro/libretro-lutro pull request #158
Opened 2021-02-02 03:50 UTC by bobparadiso

Tested with the lua snippets below.
The ogg file bgm was able to play, looping. And triggering wav and ogg sound effects at the same time worked.
Tested fine on Windows and RPi 3.

I only saw after doing this work that there was already an old ogg branch. Please merge in this code if there was a reason the other branch couldn't be used. But an rate, adding support for other audio formats in addition to WAV is important.
Thank you!

	bgm = love.audio.newSource("bgm.ogg", "stream")
	bgm:setLooping(true)
	love.audio.play(bgm)
	
	sfx1 = love.audio.newSource("sfx1.wav", "static")
	sfx2 = love.audio.newSource("sfx2.ogg", "static")
...
		if love.input.joypad("a") then
			love.audio.play(sfx1)
		end
		if love.input.joypad("b") then
			love.audio.play(sfx2)
		end

2021-02-02 11:21 UTC, kivutar requested changes
Thanks a lot for this, I'm starting a review

2021-02-02 11:21 UTC, kivutar commented on audio.c
> +      strcpy(ext, path_get_extension(path));
on OSX:

```
audio.c:165:19: error: implicit declaration of function 'path_get_extension' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      strcpy(ext, path_get_extension(path));
```

2021-02-02 11:25 UTC, kivutar commented on audio.c
> +      strcpy(ext, path_get_extension(path));
You need

```
+#include <ctype.h>
 #include <stdlib.h>
 #include <string.h>
+#include <file/file_path.h>
+#include <audio/conversion/float_to_s16.h>
```

2021-02-02 11:59 UTC, kivutar requested changes

2021-02-02 11:59 UTC, kivutar commented on audio.c
> +      printf("audio_stop");
Please remove this log too

2021-02-02 13:46 UTC, bobparadiso commented on audio.c
> +      strcpy(ext, path_get_extension(path));
done

2021-02-02 13:46 UTC, bobparadiso commented on audio.c
> +      printf("audio_stop");
and done. Thanks!

2021-02-02 15:34 UTC, bobparadiso commented
@kivutar Please let me know if there's anything else I can do to help get this feature in. Thank you very much!

2021-02-03 02:49 UTC, kivutar approved these changes

2021-02-03 02:49 UTC, merged

2021-02-03 02:50 UTC, kivutar commented
Thank you @bobparadiso 
It's very nice to finally have ogg support